### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by joseppi** [DevCrumbs/Warcraft-II#184]
### Summary: 
Sometiems all the units reply at the same time when you are moving them.
### Type: 

- A ()
- B ()
- C (x)

### Priority: 

- Urgent ()
- High ()
- Regular ()
- Low (x)

### Frequency

- Always ()
- High ()
- Regular (x)
- Low ()

### Steps to reproduce: 
Select all units, Maintain pressed right mouse button
### Actual result: 
Everyone talks saying the their lines
### Expected result: 
Just one line said.
### Build:
0.6.5

**Comment by ValdiviaDev** [comment]
When this happended to you, did you press the mouse buttons in any particular order, or were you pressing anything that wasn't the ground?
Thanks!
