### ISSUE TITLE
Invulnerable Orc

### ISSUE THREAD

**Issue by samuelkurtdavidson** [DevCrumbs/Warcraft-II#221]
![stolen_artifacts](https://user-images.githubusercontent.com/36154071/40043105-c67e92e0-5823-11e8-86da-34b0f10abd9a.png)
### Summary: 
My Archer couldn't kill the last attacking orc

### Type: 

- A ()
- B (x)
- C ()

### Priority: 

- Urgent ()
- High (x)
- Regular ()
- Low ()

### Frequency

- Always ()
- High ()
- Regular (x)
- Low ()

### Steps to reproduce: 
In lvl 1, Easy, I created an archer which was the only soldier defending my base, and the last orc left stayed after alive after hitting 0 HP

### Actual result: 
Orc that can't be killed by archer

### Expected result: 
Killable Orc

### Build:
0.9

**Comment by ValdiviaDev** [comment]
What it seems to happen here it is that the orc has very low life, but has yet not reached 0 HP.
