### ISSUE TITLE
Alliance troops stop completely

### ISSUE THREAD

**Issue by DidacRomero** [DevCrumbs/Warcraft-II#227]
### Summary: 
It seems like when you give the order to an alliance troop to attack an enemy troop andthere's a building between them That ally troop competelely frezees and is stopped forever.
### Type: 

- A ()
- B ()
- C (x)

### Priority: 

- Urgent ()
- High ()
- Regular (x)
- Low ()

### Frequency

- Always ()
- High ()
- Regular ()
- Low (x)

### Steps to reproduce: 
1-Open the game
2-Start an easy game campaign
3-give the order to an ally troop to attack an enemy whilst there is a building between them.
The Ally troop should completely freeze and stop responding.
### Actual result: 
The troop freezes forever.
### Expected result: 
The troop walks up to the necessary range and then attacks the enemy.

**Comment by ValdiviaDev** [comment]
It's not because a building is in bettween, but because an unrelated attack system issue.
