### ISSUE TITLE
Gold label does not lower when an action that requires gold is done

### ISSUE THREAD

**Issue by ValdiviaDev** [DevCrumbs/Warcraft-II#79]
### Summary: 

Label in the in game menu does not lower when doing an action that requires gold.

### Type: 

- A ()
- B (X)
- C ()

### Priority: 

- Urgent ()
- High (X)
- Regular ()
- Low ()

### Frequency

- Always (X)
- High ()
- Regular ()
- Low ()

### Steps to reproduce: 

Make an action that requires spending gold.

### Actual result: 

The in game UI label does not lower.

### Expected result: 

The in game UI label updates.

### Build:

**0.4**

**Comment by JoanValiente** [comment]
Fixed. (every time you do an action that should lower or higher the gold, you have to do "App->scene->hasGoldChanged = true;", this will update the label.)
