### ISSUE TITLE
When a building is upgraded it discounts gold even if there's not enough of it

### ISSUE THREAD

**Issue by ValdiviaDev** [DevCrumbs/Warcraft-II#80]
### Type: 

- A ()
- B (X)
- C ()

### Priority: 

- Urgent ()
- High (X)
- Regular ()
- Low ()

### Frequency

- Always (X)
- High ()
- Regular ()
- Low ()

### Steps to reproduce: 

Spend gold on a building upgrade (barracks or town hall) when there's not enough gold to upgrade it.

### Actual result: 

It does the upgrade and spends the gold anyway, arriving to negative numbers.

### Expected result: 

It does not upgrade the building and doesn't spend the gold.

### Build:

**0.4**

**Comment by JoanValiente** [comment]
Fixed.
