### ISSUE TITLE
A gold mine can be used multiple times

### ISSUE THREAD

**Issue by ValdiviaDev** [DevCrumbs/Warcraft-II#81]
### Summary: 

A gold mine can be used multiple times and acquire more gold.

### Type: 

- A ()
- B (X)
- C ()

### Priority: 

- Urgent ()
- High ()
- Regular (X)
- Low ()

### Frequency

- Always ()
- High (X)
- Regular ()
- Low ()

### Steps to reproduce: 

Press a gold mine to acquire gold, wait some time aftes getting the gold and press it again.

### Actual result: 

You do get gold again.

### Expected result: 

You do not get gold again.

### Build:

**0.4**

**Comment by JoanValiente** [comment]
Fixed.
