### ISSUE TITLE
Pig farm does not lower resources when it is destroyed

### ISSUE THREAD

**Issue by ValdiviaDev** [DevCrumbs/Warcraft-II#84]
### Type: 

- A ()
- B (X)
- C ()

### Priority: 

- Urgent ()
- High (X)
- Regular ()
- Low ()

### Frequency

- Always ()
- High (X)
- Regular ()
- Low ()

### Steps to reproduce: 

Destory a pig farm.

### Actual result: 

The total player resources do not lower.

### Expected result: 

The total player resources do lower.

### Build:

**0.4**

**Comment by JoanValiente** [comment]
Fixed.
